/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AppLogSampleRouteImport } from './routes/_app/log/sample'
import { Route as AppLogDrillholeRouteImport } from './routes/_app/log/drillhole'
import { Route as AppLogDetailsRouteImport } from './routes/_app/log/details'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppLogSampleRoute = AppLogSampleRouteImport.update({
  id: '/log/sample',
  path: '/log/sample',
  getParentRoute: () => AppRoute,
} as any)
const AppLogDrillholeRoute = AppLogDrillholeRouteImport.update({
  id: '/log/drillhole',
  path: '/log/drillhole',
  getParentRoute: () => AppRoute,
} as any)
const AppLogDetailsRoute = AppLogDetailsRouteImport.update({
  id: '/log/details',
  path: '/log/details',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/': typeof AppIndexRoute
  '/log/details': typeof AppLogDetailsRoute
  '/log/drillhole': typeof AppLogDrillholeRoute
  '/log/sample': typeof AppLogSampleRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/': typeof AppIndexRoute
  '/log/details': typeof AppLogDetailsRoute
  '/log/drillhole': typeof AppLogDrillholeRoute
  '/log/sample': typeof AppLogSampleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/log/details': typeof AppLogDetailsRoute
  '/_app/log/drillhole': typeof AppLogDrillholeRoute
  '/_app/log/sample': typeof AppLogSampleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/auth/login'
    | '/'
    | '/log/details'
    | '/log/drillhole'
    | '/log/sample'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/auth/login'
    | '/'
    | '/log/details'
    | '/log/drillhole'
    | '/log/sample'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/auth/login'
    | '/_app/'
    | '/_app/log/details'
    | '/_app/log/drillhole'
    | '/_app/log/sample'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/log/sample': {
      id: '/_app/log/sample'
      path: '/log/sample'
      fullPath: '/log/sample'
      preLoaderRoute: typeof AppLogSampleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/log/drillhole': {
      id: '/_app/log/drillhole'
      path: '/log/drillhole'
      fullPath: '/log/drillhole'
      preLoaderRoute: typeof AppLogDrillholeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/log/details': {
      id: '/_app/log/details'
      path: '/log/details'
      fullPath: '/log/details'
      preLoaderRoute: typeof AppLogDetailsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppLogDetailsRoute: typeof AppLogDetailsRoute
  AppLogDrillholeRoute: typeof AppLogDrillholeRoute
  AppLogSampleRoute: typeof AppLogSampleRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppLogDetailsRoute: AppLogDetailsRoute,
  AppLogDrillholeRoute: AppLogDrillholeRoute,
  AppLogSampleRoute: AppLogSampleRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
